from typing import Literal

from app.models.asset_forge import (
    AssetForgeAxisTripletRecord,
    AssetForgeBlockedCapabilityRecord,
    AssetForgeContextMenuActionRecord,
    AssetForgeContextMenuGroupRecord,
    AssetForgeEditorModelRecord,
    AssetForgeEditorToolRecord,
    AssetForgeEvidenceSummaryRecord,
    AssetForgeMaterialPreviewRecord,
    AssetForgeOutlinerNodeRecord,
    AssetForgePropertiesRecord,
    AssetForgePropertiesSectionRecord,
    AssetForgePropertyRowRecord,
    AssetForgePromptTemplateRecord,
    AssetForgeTimelineRecord,
    AssetForgeTransformRecord,
    AssetForgeViewportRecord,
)


AssetForgeToolGroup = Literal[
    "transform",
    "object",
    "mesh",
    "animation",
    "grease_pencil",
    "history",
    "proof",
    "review",
]

AssetForgeTruthState = Literal[
    "demo",
    "read-only",
    "plan-only",
    "preflight-only",
    "proof-only",
    "blocked",
]


def _tool(
    *,
    tool_id: str,
    label: str,
    shortcut: str | None,
    group: AssetForgeToolGroup,
    truth_state: AssetForgeTruthState,
    enabled: bool,
    selected: bool = False,
    description: str,
    blocked_reason: str | None = None,
    next_unlock: str | None = None,
    prompt_template_id: str | None = None,
) -> AssetForgeEditorToolRecord:
    return AssetForgeEditorToolRecord(
        tool_id=tool_id,
        label=label,
        shortcut=shortcut,
        group=group,
        truth_state=truth_state,
        enabled=enabled,
        selected=selected,
        description=description,
        blocked_reason=blocked_reason,
        next_unlock=next_unlock,
        prompt_template_id=prompt_template_id,
        execution_admitted=False,
        mutation_admitted=False,
    )


def build_asset_forge_editor_model() -> AssetForgeEditorModelRecord:
    prompt_templates = [
        AssetForgePromptTemplateRecord(
            template_id="inspect-candidate",
            label="Inspect candidate",
            description="Read-only candidate inspection prompt template.",
            text=(
                "Inspect candidate_id \"candidate-a\" for read-only geometry/material evidence. "
                "Do not run Blender, provider generation, Asset Processor, or O3DE mutation."
            ),
            truth_state="read-only",
            safety_labels=["read-only", "non-mutating", "auto_execute=false"],
            auto_execute=False,
        ),
        AssetForgePromptTemplateRecord(
            template_id="placement-proof-only",
            label="Placement proof-only",
            description="Create a proof-only placement candidate review packet with no runtime write admission.",
            text=(
                "Prepare editor placement proof-only review metadata for candidate-a and keep "
                "execution_admitted=false, placement_write_admitted=false, mutation_occurred=false."
            ),
            truth_state="proof-only",
            safety_labels=["proof-only", "fail-closed", "no-runtime-mutation", "auto_execute=false"],
            auto_execute=False,
        ),
        AssetForgePromptTemplateRecord(
            template_id="project-asset-preflight",
            label="Project/asset preflight",
            description="Read-only preflight checks for project path, source asset path, and evidence pointers.",
            text=(
                "Run project/asset preflight checks for source existence and evidence references only. "
                "No provider generation, no Blender execution, no project writes."
            ),
            truth_state="preflight-only",
            safety_labels=["preflight-only", "read-only", "auto_execute=false"],
            auto_execute=False,
        ),
    ]

    tools = [
        _tool(
            tool_id="transform",
            label="Transform",
            shortcut=None,
            group="transform",
            truth_state="demo",
            enabled=True,
            selected=True,
            description="UI transform mode selection only; no backend dispatch is executed.",
            prompt_template_id="inspect-candidate",
        ),
        _tool(
            tool_id="translate",
            label="Translate",
            shortcut="G",
            group="transform",
            truth_state="demo",
            enabled=True,
            description="UI translate gizmo state only; no world-space write is admitted.",
        ),
        _tool(
            tool_id="rotate",
            label="Rotate",
            shortcut="R",
            group="transform",
            truth_state="demo",
            enabled=True,
            description="UI rotate gizmo state only; no component/property mutation is admitted.",
        ),
        _tool(
            tool_id="scale",
            label="Scale",
            shortcut="S",
            group="transform",
            truth_state="demo",
            enabled=True,
            description="UI scale gizmo state only; no asset or prefab write is admitted.",
        ),
        _tool(
            tool_id="origin",
            label="Origin",
            shortcut=None,
            group="object",
            truth_state="blocked",
            enabled=False,
            description="Origin mutation remains blocked in this packet.",
            blocked_reason="Object origin mutation would write transform state and is not admitted.",
            next_unlock="Add exact transform-write admission corridor with revert/restore proof.",
        ),
        _tool(
            tool_id="object",
            label="Object",
            shortcut=None,
            group="object",
            truth_state="blocked",
            enabled=False,
            description="Object-mode mutating operations remain blocked.",
            blocked_reason="Object mutation requires runtime write admission that is intentionally out of scope.",
            next_unlock="Keep object actions read-only until a bounded admitted write corridor exists.",
        ),
        _tool(
            tool_id="duplicate",
            label="Duplicate",
            shortcut="Shift+D",
            group="object",
            truth_state="blocked",
            enabled=False,
            description="Duplication remains blocked.",
            blocked_reason="Duplicate would mutate level/prefab state and is not admitted.",
            next_unlock="Require server-owned approval and bounded prefab mutation admission.",
        ),
        _tool(
            tool_id="delete",
            label="Delete",
            shortcut="X",
            group="object",
            truth_state="blocked",
            enabled=False,
            description="Delete remains blocked.",
            blocked_reason="Delete is destructive mutation and is not admitted.",
            next_unlock="Add explicit destructive-action corridor with reversible restore proof.",
        ),
        _tool(
            tool_id="join",
            label="Join",
            shortcut="Ctrl+J",
            group="object",
            truth_state="blocked",
            enabled=False,
            description="Join remains blocked.",
            blocked_reason="Join would mutate mesh/object topology and is not admitted.",
            next_unlock="Add bounded mesh-merge admission with readback and rollback proof.",
        ),
        _tool(
            tool_id="split",
            label="Split",
            shortcut="Y",
            group="object",
            truth_state="blocked",
            enabled=False,
            description="Split remains blocked.",
            blocked_reason="Split would mutate mesh/object topology and is not admitted.",
            next_unlock="Add bounded split corridor with deterministic revert proof.",
        ),
        _tool(
            tool_id="smoothing",
            label="Smoothing",
            shortcut=None,
            group="mesh",
            truth_state="preflight-only",
            enabled=True,
            description="Preflight-only smoothing review; no material/mesh write is admitted.",
            prompt_template_id="project-asset-preflight",
        ),
        _tool(
            tool_id="smooth",
            label="Smooth",
            shortcut=None,
            group="mesh",
            truth_state="blocked",
            enabled=False,
            description="Smooth mutation remains blocked.",
            blocked_reason="Smoothing write would mutate mesh data and is not admitted.",
            next_unlock="Add narrow mesh-smoothing corridor with post-write readback.",
        ),
        _tool(
            tool_id="flat",
            label="Flat",
            shortcut=None,
            group="mesh",
            truth_state="blocked",
            enabled=False,
            description="Flat shading mutation remains blocked.",
            blocked_reason="Flat shading mutation would change material/mesh appearance and is not admitted.",
            next_unlock="Add bounded shading-write corridor with explicit rollback evidence.",
        ),
        _tool(
            tool_id="keyframes",
            label="Keyframes",
            shortcut=None,
            group="animation",
            truth_state="blocked",
            enabled=False,
            description="Keyframe mutation remains blocked.",
            blocked_reason="Animation keyframe writes are not admitted in this packet.",
            next_unlock="Add exact animation-write admission with timeline readback proof.",
        ),
        _tool(
            tool_id="insert-keyframe",
            label="Insert",
            shortcut="I",
            group="animation",
            truth_state="blocked",
            enabled=False,
            description="Insert keyframe remains blocked.",
            blocked_reason="Insert keyframe would mutate animation state and is not admitted.",
            next_unlock="Add bounded keyframe insert corridor with verification and revert.",
        ),
        _tool(
            tool_id="remove-keyframe",
            label="Remove",
            shortcut="Alt+I",
            group="animation",
            truth_state="blocked",
            enabled=False,
            description="Remove keyframe remains blocked.",
            blocked_reason="Remove keyframe is mutation and is not admitted.",
            next_unlock="Add bounded keyframe remove corridor with rollback proof.",
        ),
        _tool(
            tool_id="motion-paths",
            label="Motion Paths",
            shortcut=None,
            group="animation",
            truth_state="blocked",
            enabled=False,
            description="Motion path mutation remains blocked.",
            blocked_reason="Motion path calculation/clearing is not admitted.",
            next_unlock="Add read-only motion-path inspection before any mutation corridor.",
        ),
        _tool(
            tool_id="calculate-paths",
            label="Calculate Paths",
            shortcut=None,
            group="animation",
            truth_state="blocked",
            enabled=False,
            description="Calculate paths remains blocked.",
            blocked_reason="Path calculation triggers mutation-capable animation tooling not admitted.",
            next_unlock="Add bounded preflight and admission guard for path calculation.",
        ),
        _tool(
            tool_id="clear-paths",
            label="Clear Paths",
            shortcut=None,
            group="animation",
            truth_state="blocked",
            enabled=False,
            description="Clear paths remains blocked.",
            blocked_reason="Path clearing is mutation and not admitted.",
            next_unlock="Add explicit clear-path rollback contract before admission.",
        ),
        _tool(
            tool_id="repeat-last",
            label="Repeat Last",
            shortcut="Shift+R",
            group="history",
            truth_state="demo",
            enabled=True,
            description="UI-only repeat-last guidance; backend execution stays blocked.",
            prompt_template_id="placement-proof-only",
        ),
        _tool(
            tool_id="history",
            label="History",
            shortcut=None,
            group="history",
            truth_state="read-only",
            enabled=True,
            description="Read-only history timeline of proof records and warnings.",
        ),
        _tool(
            tool_id="grease-pencil",
            label="Grease Pencil",
            shortcut=None,
            group="grease_pencil",
            truth_state="demo",
            enabled=True,
            description="UI grease-pencil overlay mode only; no scene mutation admission.",
        ),
        _tool(
            tool_id="draw-line",
            label="Draw Line",
            shortcut="D",
            group="grease_pencil",
            truth_state="blocked",
            enabled=False,
            description="Draw line remains blocked.",
            blocked_reason="Draw-line execution would mutate scene annotations and is not admitted.",
            next_unlock="Add bounded annotation corridor with explicit non-destructive scope.",
        ),
        _tool(
            tool_id="erase",
            label="Erase",
            shortcut="E",
            group="grease_pencil",
            truth_state="blocked",
            enabled=False,
            description="Erase remains blocked.",
            blocked_reason="Erase is mutation and is not admitted.",
            next_unlock="Add explicit annotation erase policy with reversible proof.",
        ),
        _tool(
            tool_id="use-sketching",
            label="Use Sketching",
            shortcut=None,
            group="grease_pencil",
            truth_state="preflight-only",
            enabled=True,
            description="Preflight-only sketching guidance; no admitted scene mutation.",
            prompt_template_id="inspect-candidate",
        ),
    ]

    outliner = [
        AssetForgeOutlinerNodeRecord(
            node_id="scene",
            label="Scene",
            kind="scene",
            depth=0,
            truth_state="read-only",
            visible=True,
            selected=False,
        ),
        AssetForgeOutlinerNodeRecord(
            node_id="render-layers",
            label="RenderLayers",
            kind="layer",
            depth=1,
            truth_state="read-only",
            visible=True,
            selected=False,
        ),
        AssetForgeOutlinerNodeRecord(
            node_id="world",
            label="World",
            kind="world",
            depth=1,
            truth_state="read-only",
            visible=True,
            selected=False,
        ),
        AssetForgeOutlinerNodeRecord(
            node_id="cameras",
            label="Cameras",
            kind="camera_group",
            depth=1,
            truth_state="read-only",
            visible=True,
            selected=False,
        ),
        AssetForgeOutlinerNodeRecord(
            node_id="asset-root",
            label="Asset Root",
            kind="candidate_root",
            depth=1,
            truth_state="demo",
            visible=True,
            selected=True,
        ),
        AssetForgeOutlinerNodeRecord(
            node_id="mesh-lod0",
            label="Mesh_LOD0",
            kind="mesh",
            depth=2,
            truth_state="demo",
            visible=True,
            selected=True,
        ),
        AssetForgeOutlinerNodeRecord(
            node_id="materials",
            label="Materials",
            kind="material_group",
            depth=2,
            truth_state="blocked",
            visible=True,
            selected=False,
        ),
        AssetForgeOutlinerNodeRecord(
            node_id="textures",
            label="Textures",
            kind="texture_group",
            depth=2,
            truth_state="preflight-only",
            visible=True,
            selected=False,
        ),
        AssetForgeOutlinerNodeRecord(
            node_id="material-node",
            label="mesh_material_node",
            kind="material",
            depth=3,
            truth_state="blocked",
            visible=True,
            selected=False,
        ),
        AssetForgeOutlinerNodeRecord(
            node_id="texture-node",
            label="diffuse_texture_node",
            kind="texture",
            depth=3,
            truth_state="preflight-only",
            visible=True,
            selected=False,
        ),
    ]

    transform = AssetForgeTransformRecord(
        location=AssetForgeAxisTripletRecord(x=0.0, y=0.0, z=0.0, admitted=False),
        rotation=AssetForgeAxisTripletRecord(x=0.0, y=0.0, z=0.0, admitted=False),
        scale=AssetForgeAxisTripletRecord(x=1.0, y=1.0, z=1.0, admitted=False),
        dimensions=AssetForgeAxisTripletRecord(x=2.18, y=0.26, z=1.85, admitted=False),
        edit_status="blocked",
        blocked_reason=(
            "Transform editing is UI-state only in this packet; runtime transform writes are not admitted."
        ),
    )

    transform_rows = [
        AssetForgePropertyRowRecord(
            row_id="location-xyz",
            label="Location X/Y/Z",
            value=f"{transform.location.x:.3f}, {transform.location.y:.3f}, {transform.location.z:.3f}",
            truth_state="blocked",
            mutation_admitted=False,
            blocked_reason="Transform location mutation is not admitted.",
        ),
        AssetForgePropertyRowRecord(
            row_id="rotation-xyz",
            label="Rotation X/Y/Z",
            value=f"{transform.rotation.x:.3f}, {transform.rotation.y:.3f}, {transform.rotation.z:.3f}",
            truth_state="blocked",
            mutation_admitted=False,
            blocked_reason="Transform rotation mutation is not admitted.",
        ),
        AssetForgePropertyRowRecord(
            row_id="scale-xyz",
            label="Scale X/Y/Z",
            value=f"{transform.scale.x:.3f}, {transform.scale.y:.3f}, {transform.scale.z:.3f}",
            truth_state="blocked",
            mutation_admitted=False,
            blocked_reason="Transform scale mutation is not admitted.",
        ),
        AssetForgePropertyRowRecord(
            row_id="dimensions-xyz",
            label="Dimensions X/Y/Z",
            value=f"{transform.dimensions.x:.3f}, {transform.dimensions.y:.3f}, {transform.dimensions.z:.3f}",
            truth_state="preflight-only",
            mutation_admitted=False,
            blocked_reason="Dimensions are readback-style preview values only.",
        ),
    ]

    safety_rows = [
        AssetForgePropertyRowRecord(
            row_id="provider-safety",
            label="Provider generation",
            value="blocked; provider_generation_admitted=false",
            truth_state="blocked",
            mutation_admitted=False,
            blocked_reason="Provider generation execution is not admitted.",
        ),
        AssetForgePropertyRowRecord(
            row_id="blender-safety",
            label="Blender execution",
            value="blocked; blender_execution_admitted=false",
            truth_state="blocked",
            mutation_admitted=False,
            blocked_reason="Blender execution is not admitted.",
        ),
        AssetForgePropertyRowRecord(
            row_id="asset-processor-safety",
            label="Asset Processor execution",
            value="blocked; asset_processor_execution_admitted=false",
            truth_state="blocked",
            mutation_admitted=False,
            blocked_reason="Asset Processor execution is not admitted.",
        ),
        AssetForgePropertyRowRecord(
            row_id="placement-safety",
            label="Placement write",
            value="blocked; placement_write_admitted=false",
            truth_state="blocked",
            mutation_admitted=False,
            blocked_reason="Placement write execution is not admitted.",
        ),
    ]

    properties = AssetForgePropertiesRecord(
        selected_object="Weathered Ivy Arch",
        material_preview_status="preview_read_only_mutation_blocked",
        sections=[
            AssetForgePropertiesSectionRecord(
                section_id="transform",
                label="Transform",
                rows=transform_rows,
            ),
            AssetForgePropertiesSectionRecord(
                section_id="safety",
                label="Safety",
                rows=safety_rows,
            ),
        ],
        rows=[*transform_rows, *safety_rows],
    )

    material_rows = [
        AssetForgePropertyRowRecord(
            row_id="mat-diffuse",
            label="Diffuse",
            value="Lambert (read-only preview)",
            truth_state="preflight-only",
            mutation_admitted=False,
            blocked_reason="Material mutation is blocked in this packet.",
        ),
        AssetForgePropertyRowRecord(
            row_id="mat-specular",
            label="Specular",
            value="CookTorr (read-only preview)",
            truth_state="preflight-only",
            mutation_admitted=False,
            blocked_reason="Material mutation is blocked in this packet.",
        ),
        AssetForgePropertyRowRecord(
            row_id="mat-shading",
            label="Shading",
            value="Emit 0.0 / Ambient 1.0 (read-only)",
            truth_state="preflight-only",
            mutation_admitted=False,
            blocked_reason="Material mutation is blocked in this packet.",
        ),
        AssetForgePropertyRowRecord(
            row_id="mat-transparency",
            label="Transparency",
            value="blocked mutation path",
            truth_state="blocked",
            mutation_admitted=False,
            blocked_reason="Transparency mutation is blocked until explicit admission.",
        ),
    ]

    material_preview = AssetForgeMaterialPreviewRecord(
        preview_label="Preview sphere/checker",
        preview_background="checker",
        tabs=["Surface", "Wire", "Volume", "Halo"],
        active_tab="Surface",
        rows=material_rows,
        mutation_admitted=False,
        blocked_reason="Material and shading mutation are blocked in this packet.",
    )

    blocked_capabilities = [
        AssetForgeBlockedCapabilityRecord(
            capability_id="asset_forge.provider.generate",
            label="Provider generation",
            reason="Provider generation runtime execution is not admitted.",
            next_unlock="Add bounded provider admission with cost/provenance controls and review evidence.",
        ),
        AssetForgeBlockedCapabilityRecord(
            capability_id="asset_forge.blender.execute",
            label="Blender execution",
            reason="Blender runtime execution is not admitted.",
            next_unlock="Add allowlisted read-only Blender script corridor with explicit safety contract.",
        ),
        AssetForgeBlockedCapabilityRecord(
            capability_id="asset_forge.asset_processor.execute",
            label="Asset Processor execution",
            reason="Asset Processor runtime execution is not admitted in this packet.",
            next_unlock="Use read-only project evidence until a bounded processor execution corridor is admitted.",
        ),
        AssetForgeBlockedCapabilityRecord(
            capability_id="asset_forge.material.mutate",
            label="Material mutation",
            reason="Material mutation remains blocked.",
            next_unlock="Add bounded material patch corridor with backup/verify/restore proof.",
        ),
        AssetForgeBlockedCapabilityRecord(
            capability_id="asset_forge.prefab.mutate",
            label="Prefab mutation",
            reason="Prefab mutation remains blocked.",
            next_unlock="Add exact prefab mutation corridor with deterministic readback and rollback proof.",
        ),
        AssetForgeBlockedCapabilityRecord(
            capability_id="asset_forge.placement.write",
            label="Placement write",
            reason="Placement write runtime execution is not admitted.",
            next_unlock="Preserve proof-only placement packet until explicit runtime admission is approved.",
        ),
    ]

    return AssetForgeEditorModelRecord(
        source="asset-forge-editor-model",
        inspection_surface="read_only",
        editor_model_status="available",
        execution_admitted=False,
        mutation_admitted=False,
        provider_generation_admitted=False,
        blender_execution_admitted=False,
        asset_processor_execution_admitted=False,
        placement_write_admitted=False,
        active_tool_id="transform",
        viewport=AssetForgeViewportRecord(
            label="Front Ortho",
            mode="Object Mode",
            shading_modes=["Solid", "Wireframe", "Material Preview", "O3DE Preview"],
            active_shading_mode="Solid",
            grid_visible=True,
            preview_status="demo_no_real_model_loaded",
            selected_object_label="Weathered Ivy Arch",
            overlays=[
                "Axis: Z-up demo",
                "No real model loaded",
                "No provider/Blender/Asset Processor/O3DE mutation admitted",
            ],
        ),
        tools=tools,
        context_menu_groups=[
            AssetForgeContextMenuGroupRecord(
                group_id="view",
                label="View",
                actions=[
                    AssetForgeContextMenuActionRecord(
                        action_id="view-front-ortho",
                        label="Front Ortho",
                        truth_state="demo",
                        execution_admitted=False,
                        mutation_admitted=False,
                    ),
                    AssetForgeContextMenuActionRecord(
                        action_id="view-solid",
                        label="Solid",
                        truth_state="demo",
                        execution_admitted=False,
                        mutation_admitted=False,
                    ),
                    AssetForgeContextMenuActionRecord(
                        action_id="view-wireframe",
                        label="Wireframe",
                        truth_state="demo",
                        execution_admitted=False,
                        mutation_admitted=False,
                    ),
                    AssetForgeContextMenuActionRecord(
                        action_id="view-material-preview",
                        label="Material Preview",
                        truth_state="preflight-only",
                        execution_admitted=False,
                        mutation_admitted=False,
                    ),
                    AssetForgeContextMenuActionRecord(
                        action_id="view-o3de-preview",
                        label="O3DE Preview",
                        truth_state="proof-only",
                        execution_admitted=False,
                        mutation_admitted=False,
                    ),
                ],
            ),
            AssetForgeContextMenuGroupRecord(
                group_id="select",
                label="Select",
                actions=[
                    AssetForgeContextMenuActionRecord(
                        action_id="select-candidate",
                        label="Select Candidate",
                        truth_state="read-only",
                        execution_admitted=False,
                        mutation_admitted=False,
                    )
                ],
            ),
            AssetForgeContextMenuGroupRecord(
                group_id="add",
                label="Add",
                actions=[
                    AssetForgeContextMenuActionRecord(
                        action_id="add-object-blocked",
                        label="Add Object (blocked)",
                        truth_state="blocked",
                        execution_admitted=False,
                        mutation_admitted=False,
                        blocked_reason="Add object mutation is not admitted in this packet.",
                        next_unlock="Introduce bounded object-add corridor with policy and restore proof.",
                    )
                ],
            ),
            AssetForgeContextMenuGroupRecord(
                group_id="object",
                label="Object",
                actions=[
                    AssetForgeContextMenuActionRecord(
                        action_id="object-mutate-blocked",
                        label="Object mutation (blocked)",
                        truth_state="blocked",
                        execution_admitted=False,
                        mutation_admitted=False,
                        blocked_reason="Object mutation is not admitted.",
                        next_unlock="Keep object actions read-only until explicit admission.",
                    )
                ],
            ),
        ],
        outliner=outliner,
        transform=transform,
        properties=properties,
        material_preview=material_preview,
        timeline=AssetForgeTimelineRecord(
            start_frame=0,
            end_frame=240,
            current_frame=1,
            status="read_only_status_strip",
        ),
        evidence=AssetForgeEvidenceSummaryRecord(
            latest_run_id=None,
            latest_execution_id=None,
            latest_artifact_id=None,
            stage_write_evidence_reference="packet-10/stage-write-evidence.json",
            stage_write_readback_reference="packet-10/readback-evidence.json",
            stage_write_readback_status="not_run",
        ),
        prompt_templates=prompt_templates,
        blocked_capabilities=blocked_capabilities,
        next_safe_action=(
            "Select a UI tool, open a non-mutating prompt template, and review proof-only guidance in Prompt Studio."
        ),
    )
