import {
  addAllowlistedMeshMissionPromptDraft,
  cinematicPlacementProofOnlyMissionPromptDraft,
  createCinematicCameraPlaceholderMissionPromptDraft,
  createGameEntityMissionPromptDraft,
  inspectCinematicTargetMissionPromptDraft,
  inspectLoadProjectMissionPromptDraft,
  inspectProjectMissionPromptDraft,
  placementProofOnlyMissionPromptDraft,
} from "../../../lib/missionPromptTemplates";
import { createCockpitDefinition } from "./createCockpitDefinition";
import type { CockpitDefinition, CockpitNavSection } from "./cockpitRegistryTypes";

const EMPTY_PIPELINE = [
  {
    id: "launch",
    label: "Launch",
    description: "Open this cockpit and choose one bounded next action.",
    truthState: "read-only",
    blocker: "No automatic execution from launch cards.",
    nextAction: "Use command bar actions and review evidence first.",
  },
] as const;

const EMPTY_PANELS = [
  {
    id: "header",
    title: "Command strip",
    zone: "top",
    truthState: "read-only",
    contentType: "custom",
  },
  {
    id: "work-area",
    title: "Work area",
    zone: "center",
    truthState: "read-only",
    contentType: "custom",
  },
] as const;

export const cockpitDefinitions: CockpitDefinition[] = [
  createCockpitDefinition({
    id: "home",
    title: "Home",
    navLabel: "Home",
    navSubtitle: "Start here and launch mission cockpits.",
    workspaceTitle: "Home",
    workspaceSubtitle: "Mission-first launch environment with explicit truth labels and safe next steps.",
    subtitle: "Mission launcher and orientation cockpit.",
    category: "start",
    description: "Start missions, inspect truth, and route into dedicated cockpits.",
    truthState: "read-only",
    routeKey: "home",
    homeCard: {
      title: "Home",
      description: "Return to Start Here and mission overview guidance.",
      truthState: "read-only",
      primaryActionLabel: "Open Home",
      safetyNote: "Navigation-only entry surface.",
    },
    commandBar: [
      {
        id: "open-prompt",
        label: "Open Prompt Studio",
        targetWorkspaceId: "prompt",
        truthState: "read-only",
      },
    ],
    pipeline: [
      {
        id: "orient",
        label: "Orient",
        description: "Review mission truth rail and choose one mission card.",
        truthState: "read-only",
      },
      {
        id: "launch",
        label: "Launch",
        description: "Open a cockpit without auto-executing anything.",
        truthState: "read-only",
      },
    ],
    panels: [
      {
        id: "launcher",
        title: "Cockpit launcher",
        zone: "center",
        truthState: "read-only",
        contentType: "tool-cards",
      },
      {
        id: "truth-rail",
        title: "Mission truth rail",
        zone: "right",
        truthState: "unknown",
        contentType: "truth-rail",
      },
    ],
    promptTemplates: [],
    blockedCapabilities: [],
  }),
  createCockpitDefinition({
    id: "create-game",
    title: "Create Game",
    navLabel: "Create Game",
    navSubtitle: "Open the Create Game cockpit environment.",
    workspaceTitle: "Create Game",
    workspaceSubtitle: "Create Game Cockpit with staged mission workflow, bounded editor actions, and evidence review.",
    subtitle: "Build an O3DE game through safe prompt-driven stages.",
    category: "create",
    description: "Concept-to-review cockpit with bounded editor lanes and explicit blockers.",
    truthState: "admitted-real",
    routeKey: "create-game",
    homeCard: {
      title: "Create Game Cockpit",
      description: "Build a game through concept, entity, component, and review stages.",
      truthState: "admitted-real",
      primaryActionLabel: "Open Create Game",
      safetyNote: "Narrow admitted lanes only; broad mutation remains blocked.",
    },
    commandBar: [
      { id: "inspect-project", label: "Inspect Project", targetWorkspaceId: "prompt", truthState: "read-only" },
      { id: "open-prompt", label: "Open Prompt Studio", targetWorkspaceId: "prompt", truthState: "read-only" },
      { id: "open-asset-forge", label: "Open Asset Forge", targetWorkspaceId: "asset-forge", truthState: "plan-only" },
      { id: "open-runtime", label: "Open Runtime", targetWorkspaceId: "runtime", truthState: "preflight-only" },
      { id: "open-records", label: "Open Records", targetWorkspaceId: "records", truthState: "read-only" },
    ],
    pipeline: [
      {
        id: "concept",
        label: "Concept",
        description: "Define genre, objective, and core loop.",
        truthState: "plan-only",
        blocker: "Full automatic game generation is not admitted.",
        nextAction: "Inspect project or draft a read-only plan.",
      },
      {
        id: "project-target",
        label: "Project Target",
        description: "Verify project root, bridge, and adapter mode.",
        truthState: "preflight-only",
        blocker: "Project creation/registration is not admitted.",
        nextAction: "Run a read-only project inspect step.",
      },
      {
        id: "level",
        label: "Level",
        description: "Open one known level through typed controls.",
        truthState: "admitted-real",
        blocker: "Broad level rewrites remain blocked.",
        nextAction: "Open one level and verify readback.",
      },
      {
        id: "entities",
        label: "Gameplay Entities",
        description: "Create one root-level named entity.",
        truthState: "admitted-real",
        blocker: "Hierarchy rewrites and prefab mutation are blocked.",
        nextAction: "Create one safe entity and review evidence.",
      },
      {
        id: "components",
        label: "Components",
        description: "Add allowlisted components such as Mesh.",
        truthState: "admitted-real",
        blocker: "Arbitrary component/property writes are blocked.",
        nextAction: "Use allowlisted component template.",
      },
      {
        id: "assets",
        label: "Assets",
        description: "Review candidate and staging context in Asset Forge.",
        truthState: "proof-only",
        blocker: "Provider generation and broad asset mutation are blocked.",
        nextAction: "Open Asset Forge pipeline.",
      },
      {
        id: "validation",
        label: "Validation",
        description: "Review runs/executions/artifacts for confidence.",
        truthState: "preflight-only",
        blocker: "Broad build/test execution is not admitted.",
        nextAction: "Open Runtime and Records.",
      },
    ],
    panels: [
      { id: "command-strip", title: "Command strip", zone: "top", truthState: "read-only", contentType: "custom" },
      { id: "game-tools", title: "Game tools", zone: "left", truthState: "admitted-real", contentType: "tool-cards" },
      { id: "game-pipeline", title: "Game pipeline", zone: "center", truthState: "admitted-real", contentType: "pipeline" },
      { id: "game-inspector", title: "Inspector and truth", zone: "right", truthState: "preflight-only", contentType: "truth-rail" },
      { id: "game-evidence", title: "Evidence and prompts", zone: "bottom", truthState: "read-only", contentType: "prompt-templates" },
    ],
    promptTemplates: [
      {
        id: "inspect-project",
        label: inspectProjectMissionPromptDraft.label,
        description: inspectProjectMissionPromptDraft.guidance,
        text: inspectProjectMissionPromptDraft.promptText,
        truthState: "read-only",
        safetyLabels: inspectProjectMissionPromptDraft.truthLabels,
        autoExecute: false,
      },
      {
        id: "create-safe-entity",
        label: createGameEntityMissionPromptDraft.label,
        description: createGameEntityMissionPromptDraft.guidance,
        text: createGameEntityMissionPromptDraft.promptText,
        truthState: "admitted-real",
        safetyLabels: createGameEntityMissionPromptDraft.truthLabels,
        autoExecute: false,
      },
      {
        id: "add-allowlisted-mesh",
        label: addAllowlistedMeshMissionPromptDraft.label,
        description: addAllowlistedMeshMissionPromptDraft.guidance,
        text: addAllowlistedMeshMissionPromptDraft.promptText,
        truthState: "admitted-real",
        safetyLabels: addAllowlistedMeshMissionPromptDraft.truthLabels,
        autoExecute: false,
      },
    ],
    blockedCapabilities: [
      {
        id: "full-game-generation",
        label: "Full game generation blocked",
        reason: "Autonomous wide generation remains outside admitted boundaries.",
        nextUnlock: "Exact admission packet with bounded scope and reversible proof.",
      },
      {
        id: "prefab-mutation",
        label: "Prefab mutation blocked",
        reason: "High-risk scene mutation remains non-admitted.",
        nextUnlock: "Separate prefab corridor with revert/restore proof.",
      },
      {
        id: "arbitrary-scripts",
        label: "Arbitrary shell/python/editor scripts blocked",
        reason: "Typed planner only; arbitrary script execution is forbidden.",
        nextUnlock: "Future bounded script lane with explicit review controls.",
      },
    ],
  }),
  createCockpitDefinition({
    id: "create-movie",
    title: "Create Movie",
    navLabel: "Create Movie",
    navSubtitle: "Open the Create Movie cockpit environment.",
    workspaceTitle: "Create Movie",
    workspaceSubtitle: "Create Movie Cockpit with cinematic planning, proof-only placement review, and explicit blockers.",
    subtitle: "Build cinematic scenes and evidence through safe stages.",
    category: "create",
    description: "Cinematic cockpit with narrow editor actions and proof-only placement review.",
    truthState: "admitted-real",
    routeKey: "create-movie",
    homeCard: {
      title: "Create Movie Cockpit",
      description: "Plan shots, camera placeholders, and proof-only prop placement.",
      truthState: "proof-only",
      primaryActionLabel: "Open Create Movie",
      safetyNote: "Render/export and placement writes remain blocked.",
    },
    commandBar: [
      { id: "inspect-cinematic", label: "Inspect Cinematic Target", targetWorkspaceId: "prompt", truthState: "read-only" },
      { id: "open-prompt", label: "Open Prompt Studio", targetWorkspaceId: "prompt", truthState: "read-only" },
      { id: "open-asset-forge", label: "Open Asset Forge", targetWorkspaceId: "asset-forge", truthState: "proof-only" },
      { id: "open-runtime", label: "Open Runtime", targetWorkspaceId: "runtime", truthState: "preflight-only" },
      { id: "open-records", label: "Open Records", targetWorkspaceId: "records", truthState: "read-only" },
    ],
    pipeline: [
      { id: "story", label: "Story / Shot Plan", description: "Outline sequence, mood, and camera intent.", truthState: "plan-only", blocker: "Full movie generation is not admitted.", nextAction: "Draft read-only cinematic plan." },
      { id: "target", label: "Project Target", description: "Verify project, bridge, and adapter posture.", truthState: "preflight-only", blocker: "Target mutation remains blocked.", nextAction: "Inspect cinematic target." },
      { id: "scene", label: "Level / Scene", description: "Open one known level with narrow controls.", truthState: "admitted-real", blocker: "Broad scene rewrites are blocked.", nextAction: "Open one level and verify readback." },
      { id: "camera", label: "Camera", description: "Create placeholder camera entity only.", truthState: "admitted-real", blocker: "Broad camera animation writes are blocked.", nextAction: "Use camera placeholder template." },
      { id: "props", label: "Characters / Props", description: "Review stage and placement proof-only candidates.", truthState: "proof-only", blocker: "Placement write remains non-admitted.", nextAction: "Use proof-only placement template." },
      { id: "review", label: "Sequence / Review", description: "Review evidence and blockers before next packet.", truthState: "read-only", blocker: "Review does not admit mutation.", nextAction: "Open Records." },
    ],
    panels: [
      { id: "command-strip", title: "Command strip", zone: "top", truthState: "read-only", contentType: "custom" },
      { id: "movie-tools", title: "Movie tools", zone: "left", truthState: "admitted-real", contentType: "tool-cards" },
      { id: "movie-pipeline", title: "Cinematic pipeline", zone: "center", truthState: "proof-only", contentType: "pipeline" },
      { id: "movie-inspector", title: "Inspector and truth", zone: "right", truthState: "preflight-only", contentType: "truth-rail" },
      { id: "movie-evidence", title: "Evidence and prompts", zone: "bottom", truthState: "read-only", contentType: "prompt-templates" },
    ],
    promptTemplates: [
      {
        id: "inspect-cinematic",
        label: inspectCinematicTargetMissionPromptDraft.label,
        description: inspectCinematicTargetMissionPromptDraft.guidance,
        text: inspectCinematicTargetMissionPromptDraft.promptText,
        truthState: "read-only",
        safetyLabels: inspectCinematicTargetMissionPromptDraft.truthLabels,
        autoExecute: false,
      },
      {
        id: "camera-placeholder",
        label: createCinematicCameraPlaceholderMissionPromptDraft.label,
        description: createCinematicCameraPlaceholderMissionPromptDraft.guidance,
        text: createCinematicCameraPlaceholderMissionPromptDraft.promptText,
        truthState: "admitted-real",
        safetyLabels: createCinematicCameraPlaceholderMissionPromptDraft.truthLabels,
        autoExecute: false,
      },
      {
        id: "placement-proof-only",
        label: cinematicPlacementProofOnlyMissionPromptDraft.label,
        description: cinematicPlacementProofOnlyMissionPromptDraft.guidance,
        text: cinematicPlacementProofOnlyMissionPromptDraft.promptText,
        truthState: "proof-only",
        safetyLabels: cinematicPlacementProofOnlyMissionPromptDraft.truthLabels,
        autoExecute: false,
      },
    ],
    blockedCapabilities: [
      {
        id: "render-export",
        label: "Render/export automation blocked",
        reason: "Render and export automation remain non-admitted.",
        nextUnlock: "Dedicated render corridor with bounded runtime controls.",
      },
      {
        id: "material-mutation",
        label: "Lighting/material mutation blocked",
        reason: "High-risk render domain requires separate admission and rollback proof.",
        nextUnlock: "Material/lighting packet with explicit approval and revert strategy.",
      },
    ],
  }),
  createCockpitDefinition({
    id: "load-project",
    title: "Load Project",
    navLabel: "Load Project",
    navSubtitle: "Open the Load Project cockpit environment.",
    workspaceTitle: "Load Project",
    workspaceSubtitle: "Load Project Cockpit for read-only target verification and preflight readiness checks.",
    subtitle: "Connect, inspect, and verify the active project target.",
    category: "create",
    description: "Read-only and preflight cockpit for target readiness before authoring.",
    truthState: "read-only",
    routeKey: "load-project",
    homeCard: {
      title: "Load Project Cockpit",
      description: "Verify project root, bridge status, and readiness before authoring.",
      truthState: "read-only",
      primaryActionLabel: "Open Load Project",
      safetyNote: "No project file writes in this packet.",
    },
    commandBar: [
      { id: "inspect-project", label: "Inspect Project", targetWorkspaceId: "prompt", truthState: "read-only" },
      { id: "refresh-status", label: "Refresh Target Status", targetWorkspaceId: "runtime", truthState: "preflight-only" },
      { id: "open-records", label: "Open Records", targetWorkspaceId: "records", truthState: "read-only" },
    ],
    pipeline: [
      { id: "project-root", label: "Project root selected", description: "Confirm active project root target.", truthState: "read-only", blocker: "Unknown target blocks safe authoring.", nextAction: "Run inspect prompt." },
      { id: "bridge", label: "Editor bridge configured", description: "Verify bridge configuration and heartbeat.", truthState: "preflight-only", blocker: "Bridge unavailable means stale assumptions.", nextAction: "Open Runtime overview." },
      { id: "adapter", label: "Adapter mode known", description: "Confirm adapter mode and execution boundaries.", truthState: "preflight-only", blocker: "Unknown mode blocks confidence.", nextAction: "Refresh adapters/readiness." },
      { id: "inspect", label: "Project inspect available", description: "Ensure read-only project inspect is available.", truthState: "read-only", blocker: "No inspect evidence means no safe mutation baseline.", nextAction: "Run inspect template." },
    ],
    panels: [
      { id: "command-strip", title: "Command strip", zone: "top", truthState: "read-only", contentType: "custom" },
      { id: "load-tools", title: "Load project tools", zone: "left", truthState: "read-only", contentType: "tool-cards" },
      { id: "load-checklist", title: "Project checklist", zone: "center", truthState: "preflight-only", contentType: "pipeline" },
      { id: "load-inspector", title: "Target summary and truth", zone: "right", truthState: "unknown", contentType: "truth-rail" },
      { id: "load-evidence", title: "Evidence and prompts", zone: "bottom", truthState: "read-only", contentType: "prompt-templates" },
    ],
    promptTemplates: [
      {
        id: "inspect-load-project",
        label: inspectLoadProjectMissionPromptDraft.label,
        description: inspectLoadProjectMissionPromptDraft.guidance,
        text: inspectLoadProjectMissionPromptDraft.promptText,
        truthState: "read-only",
        safetyLabels: inspectLoadProjectMissionPromptDraft.truthLabels,
        autoExecute: false,
      },
    ],
    blockedCapabilities: [
      {
        id: "project-registration",
        label: "Register/create project blocked",
        reason: "This cockpit is read-only and preflight-only in this packet.",
        nextUnlock: "Future admitted project registration corridor.",
      },
      {
        id: "gem-mutation",
        label: "Enable/disable Gems blocked",
        reason: "Gem mutation is out of scope and non-admitted.",
        nextUnlock: "Separate Gem governance packet.",
      },
    ],
  }),
  createCockpitDefinition({
    id: "asset-forge",
    title: "Asset Forge",
    navLabel: "Asset Forge",
    navSubtitle: "Open the O3DE-native asset studio workspace.",
    workspaceTitle: "Asset Forge",
    workspaceSubtitle: "Asset Forge cockpit with left tools, center studio, right inspector, and bottom evidence drawer.",
    subtitle: "Candidate, staging, and placement-proof workflow cockpit.",
    category: "create",
    description: "Asset cockpit with explicit blocked generation/mutation gates and proof-only placement review.",
    truthState: "proof-only",
    routeKey: "asset-forge",
    homeCard: {
      title: "Asset Forge Cockpit",
      description: "Review candidates, stage plans, readback, and placement proof-only evidence.",
      truthState: "proof-only",
      primaryActionLabel: "Open Asset Forge",
      safetyNote: "Provider, Blender, Asset Processor, placement execution, and mutation remain blocked.",
    },
    commandBar: [
      { id: "open-prompt", label: "Open Prompt Studio", targetWorkspaceId: "prompt", truthState: "read-only" },
      { id: "open-runtime", label: "Open Runtime", targetWorkspaceId: "runtime", truthState: "preflight-only" },
      { id: "open-records", label: "Open Records", targetWorkspaceId: "records", truthState: "read-only" },
      { id: "open-builder", label: "Open Builder", targetWorkspaceId: "builder", truthState: "read-only" },
    ],
    pipeline: [
      { id: "describe", label: "Describe", description: "Capture asset intent and constraints.", truthState: "plan-only", blocker: "Provider execution not admitted.", nextAction: "Use candidate plan lanes." },
      { id: "candidate", label: "Candidate", description: "Select and inspect candidate metadata.", truthState: "demo", blocker: "Real generation is blocked.", nextAction: "Review candidate evidence." },
      { id: "preflight", label: "Preflight", description: "Check provider and Blender readiness signals.", truthState: "preflight-only", blocker: "Blender/provider execution blocked.", nextAction: "Review readiness only." },
      { id: "stage-plan", label: "Stage Plan", description: "Plan bounded O3DE source staging.", truthState: "plan-only", blocker: "Write corridor requires exact constraints.", nextAction: "Review stage plan status." },
      { id: "stage-write", label: "Stage Write", description: "Bounded staging corridor when explicitly gated.", truthState: "gated-real", blocker: "No broad project writes allowed.", nextAction: "Verify readback evidence." },
      { id: "readback", label: "Readback", description: "Verify staged source and references.", truthState: "preflight-only", blocker: "Missing readback evidence blocks proof continuation.", nextAction: "Check evidence references." },
      { id: "placement-proof", label: "Placement Proof", description: "Record proof-only placement candidate.", truthState: "fail-closed", blocker: "execution_admitted=false and placement_write_admitted=false.", nextAction: "Review fail-closed output and blockers." },
      { id: "review", label: "Review", description: "Explain what happened and what remains blocked.", truthState: "read-only", blocker: "None for review; mutation remains blocked.", nextAction: "Open Records evidence timeline." },
    ],
    panels: [
      { id: "asset-forge-command-strip", title: "Command strip", zone: "top", truthState: "read-only", contentType: "custom" },
      { id: "asset-forge-left-tools", title: "Left tools and candidates", zone: "left", truthState: "plan-only", contentType: "tool-cards" },
      { id: "asset-forge-center-work", title: "Center dominant studio surface", zone: "center", truthState: "demo", contentType: "viewport" },
      { id: "asset-forge-right-inspector", title: "Right inspector and truth", zone: "right", truthState: "preflight-only", contentType: "inspector" },
      { id: "asset-forge-bottom-evidence", title: "Bottom evidence and prompts", zone: "bottom", truthState: "read-only", contentType: "evidence" },
    ],
    promptTemplates: [
      {
        id: "inspect-project",
        label: inspectProjectMissionPromptDraft.label,
        description: inspectProjectMissionPromptDraft.guidance,
        text: inspectProjectMissionPromptDraft.promptText,
        truthState: "read-only",
        safetyLabels: inspectProjectMissionPromptDraft.truthLabels,
        autoExecute: false,
      },
      {
        id: "placement-proof",
        label: placementProofOnlyMissionPromptDraft.label,
        description: placementProofOnlyMissionPromptDraft.guidance,
        text: placementProofOnlyMissionPromptDraft.promptText,
        truthState: "proof-only",
        safetyLabels: placementProofOnlyMissionPromptDraft.truthLabels,
        autoExecute: false,
      },
    ],
    blockedCapabilities: [
      {
        id: "provider-generation",
        label: "Provider generation blocked",
        reason: "Provider execution/spend is non-admitted in this packet.",
        nextUnlock: "Bounded provider corridor with explicit runtime controls.",
      },
      {
        id: "blender-execution",
        label: "Blender execution blocked",
        reason: "Blender execution remains non-admitted.",
        nextUnlock: "Dedicated Blender execution corridor with readback safeguards.",
      },
      {
        id: "asset-processor-execution",
        label: "Asset Processor execution blocked",
        reason: "Asset Processor mutation corridor is non-admitted.",
        nextUnlock: "Separate AP packet with bounded mutation and revert proof.",
      },
      {
        id: "placement-write",
        label: "Placement execution/write blocked",
        reason: "execution_admitted=false, placement_write_admitted=false, mutation_occurred=false.",
        nextUnlock: "Exact placement admission corridor with readback and revert/restore proof.",
      },
    ],
  }),
  createCockpitDefinition({
    id: "prompt",
    title: "Prompt Studio",
    navLabel: "Prompt Studio",
    navSubtitle: "Compose and review prompt plans before execution.",
    workspaceTitle: "Prompt Studio",
    workspaceSubtitle: "Prompt planning and review workspace with source-aware handoff context.",
    subtitle: "Prompt planning and bounded execution controls.",
    category: "build",
    description: "Prompt workspace for plan preview and explicit operator review.",
    truthState: "read-only",
    routeKey: "prompt",
    homeCard: {
      title: "Prompt Studio",
      description: "Open prompt planning and template review lanes.",
      truthState: "read-only",
      primaryActionLabel: "Open Prompt Studio",
      safetyNote: "No auto execution from Home launcher.",
    },
    commandBar: [
      { id: "open-home", label: "Open Home", targetWorkspaceId: "home", truthState: "read-only" },
    ],
    pipeline: [...EMPTY_PIPELINE],
    panels: [...EMPTY_PANELS],
    promptTemplates: [],
    blockedCapabilities: [],
  }),
  createCockpitDefinition({
    id: "builder",
    title: "Builder",
    navLabel: "Builder",
    navSubtitle: "Lane coordination and cockpit definition tooling.",
    workspaceTitle: "Builder",
    workspaceSubtitle: "Builder cockpit for lane coordination and cockpit scaffolding support.",
    subtitle: "Mission board, worktree lifecycle, and cockpit builder tooling.",
    category: "build",
    description: "Builder workspace for coordination and cockpit-definition scaffolding.",
    truthState: "read-only",
    routeKey: "builder",
    homeCard: {
      title: "Builder",
      description: "Open Builder for lane coordination and cockpit definition preview.",
      truthState: "read-only",
      primaryActionLabel: "Open Builder",
      safetyNote: "Builder panel in this slice is frontend-only and does not write files.",
    },
    commandBar: [
      { id: "open-cockpit-builder", label: "Open Cockpit Builder panel", targetWorkspaceId: "builder", truthState: "read-only" },
    ],
    pipeline: [...EMPTY_PIPELINE],
    panels: [...EMPTY_PANELS],
    promptTemplates: [],
    blockedCapabilities: [],
  }),
  createCockpitDefinition({
    id: "operations",
    title: "Operations",
    navLabel: "Operations",
    navSubtitle: "Dispatch, approvals, and timeline coordination.",
    workspaceTitle: "Operations",
    workspaceSubtitle: "Operations coordination workspace for dispatch, approvals, and timeline.",
    subtitle: "Operational coordination cockpit.",
    category: "operate",
    description: "Operations workspace for dispatch and live coordination.",
    truthState: "read-only",
    routeKey: "operations",
    homeCard: {
      title: "Operations",
      description: "Open operational dispatch and approval views.",
      truthState: "read-only",
      primaryActionLabel: "Open Operations",
      safetyNote: "Navigation only from Home launcher.",
    },
    commandBar: [],
    pipeline: [...EMPTY_PIPELINE],
    panels: [...EMPTY_PANELS],
    promptTemplates: [],
    blockedCapabilities: [],
  }),
  createCockpitDefinition({
    id: "runtime",
    title: "Runtime",
    navLabel: "Runtime",
    navSubtitle: "Bridge health, executors, and readiness truth.",
    workspaceTitle: "Runtime",
    workspaceSubtitle: "Runtime workspace for bridge status, executor lanes, and governance signals.",
    subtitle: "Runtime health and readiness cockpit.",
    category: "operate",
    description: "Runtime health cockpit for bridge and adapter truth.",
    truthState: "preflight-only",
    routeKey: "runtime",
    homeCard: {
      title: "Runtime",
      description: "Open runtime status and bridge/adapters readiness.",
      truthState: "preflight-only",
      primaryActionLabel: "Open Runtime",
      safetyNote: "Telemetry review only.",
    },
    commandBar: [],
    pipeline: [...EMPTY_PIPELINE],
    panels: [...EMPTY_PANELS],
    promptTemplates: [],
    blockedCapabilities: [],
  }),
  createCockpitDefinition({
    id: "records",
    title: "Records",
    navLabel: "Records",
    navSubtitle: "Persisted runs, executions, artifacts, and evidence.",
    workspaceTitle: "Records",
    workspaceSubtitle: "Records workspace for run/execution/artifact evidence review.",
    subtitle: "Evidence review cockpit.",
    category: "inspect",
    description: "Records workspace for evidence-first review.",
    truthState: "read-only",
    routeKey: "records",
    homeCard: {
      title: "Records",
      description: "Open records and evidence timelines.",
      truthState: "read-only",
      primaryActionLabel: "Open Records",
      safetyNote: "Review-only; no mutation.",
    },
    commandBar: [],
    pipeline: [...EMPTY_PIPELINE],
    panels: [...EMPTY_PANELS],
    promptTemplates: [],
    blockedCapabilities: [],
  }),
];

export const cockpitNavSections: CockpitNavSection[] = [
  {
    id: "start",
    label: "Start",
    detail: "Orient first and launch a mission cockpit.",
    cockpitIds: ["home"],
  },
  {
    id: "create",
    label: "Create",
    detail: "Build content through bounded cockpit workflows.",
    cockpitIds: ["create-game", "create-movie", "load-project", "asset-forge"],
  },
  {
    id: "build",
    label: "Build",
    detail: "Prompt and builder control surfaces.",
    cockpitIds: ["prompt", "builder"],
  },
  {
    id: "operate",
    label: "Operate",
    detail: "Coordinate operations and runtime posture.",
    cockpitIds: ["operations", "runtime"],
  },
  {
    id: "inspect",
    label: "Inspect",
    detail: "Review persisted evidence and outcomes.",
    cockpitIds: ["records"],
  },
];
