import { getShellWorkspaceGuide } from "../../../content/operatorGuideShell";

import { createCockpitDefinition } from "./createCockpitDefinition";
import type { CockpitDefinition } from "./cockpitRegistryTypes";

const homeGuide = getShellWorkspaceGuide("home");
const promptGuide = getShellWorkspaceGuide("prompt");
const builderGuide = getShellWorkspaceGuide("builder");
const operationsGuide = getShellWorkspaceGuide("operations");
const runtimeGuide = getShellWorkspaceGuide("runtime");
const recordsGuide = getShellWorkspaceGuide("records");

export const cockpitDefinitions: readonly CockpitDefinition[] = [
  createCockpitDefinition({
    id: "home",
    routeKey: "home",
    category: "start",
    title: homeGuide.workspaceTitle,
    navLabel: homeGuide.navLabel,
    navSubtitle: homeGuide.navSubtitle,
    workspaceSubtitle: homeGuide.workspaceSubtitle,
    description: "Start, orient, and launch first-class cockpit apps from one calm control surface.",
    truthState: "read-only",
    navTone: "info",
    navTooltip: homeGuide.tooltip,
    showInHomeLauncher: false,
    homeCard: {
      title: "Home",
      description: "Overview and launcher cockpit.",
      truthState: "read-only",
      primaryActionLabel: "Open Home",
      safetyNote: "Read-only orientation surface.",
    },
    panels: [
      { id: "home-top", title: "Start strip", zone: "top", contentType: "custom" },
      { id: "home-left", title: "Launch tools", zone: "left", contentType: "tool-cards" },
      { id: "home-center", title: "Overview workspace", zone: "center", contentType: "custom" },
      { id: "home-right", title: "Inspector", zone: "right", contentType: "inspector" },
      { id: "home-bottom", title: "Evidence drawer", zone: "bottom", contentType: "evidence" },
    ],
  }),
  createCockpitDefinition({
    id: "create-game",
    routeKey: "create-game",
    category: "create",
    title: "Create Game",
    navLabel: "Create Game",
    navSubtitle: "First-class game cockpit",
    workspaceSubtitle: "Create Game Cockpit with staged mission workflow, bounded editor actions, and evidence review.",
    description: "Build game workflows through admitted narrow editor lanes with explicit blockers and evidence.",
    truthState: "admitted-real",
    navTone: "success",
    navTooltip: "Open the first-class Create Game cockpit with pipeline, tools, and blocked-capability guidance.",
    showInHomeLauncher: true,
    homeCard: {
      title: "Create Game",
      description: "Stage concept, level, entity, component, and review steps in a dedicated cockpit.",
      truthState: "admitted-real",
      primaryActionLabel: "Open Create Game",
      safetyNote: "Narrow admitted editor actions only; broad mutation remains blocked.",
    },
    panels: [
      { id: "create-game-top", title: "Pipeline strip", zone: "top", contentType: "pipeline" },
      { id: "create-game-left", title: "Tools", zone: "left", contentType: "tool-cards" },
      { id: "create-game-center", title: "Primary work", zone: "center", contentType: "custom" },
      { id: "create-game-right", title: "Truth and blockers", zone: "right", contentType: "truth-rail" },
      { id: "create-game-bottom", title: "Evidence drawer", zone: "bottom", contentType: "evidence" },
    ],
  }),
  createCockpitDefinition({
    id: "create-movie",
    routeKey: "create-movie",
    category: "create",
    title: "Create Movie",
    navLabel: "Create Movie",
    navSubtitle: "First-class cinematic cockpit",
    workspaceSubtitle: "Create Movie Cockpit with cinematic planning, proof-only placement review, and explicit blockers.",
    description: "Plan cinematic lanes with narrow editor actions and proof-only placement review.",
    truthState: "proof-only",
    navTone: "info",
    navTooltip: "Open the first-class Create Movie cockpit for cinematic pipeline and proof-only placement guidance.",
    showInHomeLauncher: true,
    homeCard: {
      title: "Create Movie",
      description: "Cinematic planning, camera placeholders, and proof-only prop workflow.",
      truthState: "proof-only",
      primaryActionLabel: "Open Create Movie",
      safetyNote: "Placement writes and render/export automation remain blocked.",
    },
    panels: [
      { id: "create-movie-top", title: "Pipeline strip", zone: "top", contentType: "pipeline" },
      { id: "create-movie-left", title: "Tools", zone: "left", contentType: "tool-cards" },
      { id: "create-movie-center", title: "Primary work", zone: "center", contentType: "custom" },
      { id: "create-movie-right", title: "Truth and blockers", zone: "right", contentType: "truth-rail" },
      { id: "create-movie-bottom", title: "Evidence drawer", zone: "bottom", contentType: "evidence" },
    ],
  }),
  createCockpitDefinition({
    id: "load-project",
    routeKey: "load-project",
    category: "create",
    title: "Load Project",
    navLabel: "Load Project",
    navSubtitle: "First-class preflight cockpit",
    workspaceSubtitle: "Load Project Cockpit for read-only target verification and preflight readiness checks.",
    description: "Verify target assumptions before entering authoring workflows.",
    truthState: "preflight-only",
    navTone: "neutral",
    navTooltip: "Open Load Project cockpit for target verification and configuration preflight.",
    showInHomeLauncher: true,
    homeCard: {
      title: "Load Project",
      description: "Inspect project root, bridge health, adapters, and readiness before authoring.",
      truthState: "preflight-only",
      primaryActionLabel: "Open Load Project",
      safetyNote: "No project file writes or registration in this cockpit.",
    },
    panels: [
      { id: "load-project-top", title: "Checklist strip", zone: "top", contentType: "pipeline" },
      { id: "load-project-left", title: "Tools", zone: "left", contentType: "tool-cards" },
      { id: "load-project-center", title: "Target workspace", zone: "center", contentType: "custom" },
      { id: "load-project-right", title: "Truth and inspector", zone: "right", contentType: "truth-rail" },
      { id: "load-project-bottom", title: "Evidence drawer", zone: "bottom", contentType: "evidence" },
    ],
  }),
  createCockpitDefinition({
    id: "asset-forge",
    routeKey: "asset-forge",
    category: "create",
    title: "Asset Forge",
    navLabel: "Asset Forge",
    navSubtitle: "O3DE-native asset studio",
    workspaceSubtitle: "O3DE-native production asset toolbench with read-only evidence, review, and gated creation planning.",
    description: "Creator cockpit for candidate planning, proof-only placement review, and evidence-first analysis.",
    truthState: "proof-only",
    navTone: "info",
    navTooltip: "Open Asset Forge cockpit with left tools, dominant center studio, right truth rail, and bottom evidence drawer.",
    showInHomeLauncher: true,
    homeCard: {
      title: "Asset Forge",
      description: "Creator cockpit for candidate asset workflows and fail-closed placement proof planning.",
      truthState: "proof-only",
      primaryActionLabel: "Open Asset Forge",
      safetyNote: "Provider generation, Blender execution, and placement write remain blocked.",
    },
    panels: [
      { id: "asset-forge-top", title: "Guided pipeline strip", zone: "top", contentType: "pipeline" },
      { id: "asset-forge-left", title: "Tools and outliner", zone: "left", contentType: "tool-cards" },
      { id: "asset-forge-center", title: "Studio viewport", zone: "center", contentType: "viewport" },
      { id: "asset-forge-right", title: "Inspector and truth rail", zone: "right", contentType: "truth-rail" },
      { id: "asset-forge-bottom", title: "Evidence and prompts drawer", zone: "bottom", contentType: "evidence" },
    ],
  }),
  createCockpitDefinition({
    id: "prompt",
    routeKey: "prompt",
    category: "build",
    title: promptGuide.workspaceTitle,
    navLabel: promptGuide.navLabel,
    navSubtitle: promptGuide.navSubtitle,
    workspaceSubtitle: promptGuide.workspaceSubtitle,
    description: "Natural-language cockpit with preview and approval guardrails.",
    truthState: "plan-only",
    navTone: "info",
    navTooltip: promptGuide.tooltip,
    showInHomeLauncher: true,
    homeCard: {
      title: "Prompt Studio",
      description: "Prepare prompts with prefill-only templates and explicit approval boundaries.",
      truthState: "plan-only",
      primaryActionLabel: "Open Prompt Studio",
      safetyNote: "No auto-execution from cockpit launches.",
    },
    panels: [
      { id: "prompt-top", title: "Command strip", zone: "top", contentType: "pipeline" },
      { id: "prompt-left", title: "Tools", zone: "left", contentType: "tool-cards" },
      { id: "prompt-center", title: "Prompt editor", zone: "center", contentType: "custom" },
      { id: "prompt-right", title: "Inspector", zone: "right", contentType: "inspector" },
      { id: "prompt-bottom", title: "Evidence drawer", zone: "bottom", contentType: "evidence" },
    ],
  }),
  createCockpitDefinition({
    id: "builder",
    routeKey: "builder",
    category: "build",
    title: builderGuide.workspaceTitle,
    navLabel: builderGuide.navLabel,
    navSubtitle: builderGuide.navSubtitle,
    workspaceSubtitle: builderGuide.workspaceSubtitle,
    description: "Worktree and coordination cockpit with mission-board, lane, and autonomy surfaces.",
    truthState: "read-only",
    navTone: "info",
    navTooltip: builderGuide.tooltip,
    showInHomeLauncher: true,
    homeCard: {
      title: "Builder",
      description: "Manage worktree lanes, mission control, active lane operations, and autonomy inbox.",
      truthState: "read-only",
      primaryActionLabel: "Open Builder",
      safetyNote: "Workspace coordination cockpit; does not widen runtime admission.",
    },
    panels: [
      { id: "builder-top", title: "Surface strip", zone: "top", contentType: "pipeline" },
      { id: "builder-left", title: "Tools and outliner", zone: "left", contentType: "tool-cards" },
      { id: "builder-center", title: "Primary work area", zone: "center", contentType: "custom" },
      { id: "builder-right", title: "Inspector", zone: "right", contentType: "inspector" },
      { id: "builder-bottom", title: "Recommendations drawer", zone: "bottom", contentType: "evidence" },
    ],
  }),
  createCockpitDefinition({
    id: "operations",
    routeKey: "operations",
    category: "operate",
    title: operationsGuide.workspaceTitle,
    navLabel: operationsGuide.navLabel,
    navSubtitle: operationsGuide.navSubtitle,
    workspaceSubtitle: operationsGuide.workspaceSubtitle,
    description: "Dispatch, agents, approvals, and timeline cockpit.",
    truthState: "read-only",
    navTone: "neutral",
    navTooltip: operationsGuide.tooltip,
    showInHomeLauncher: true,
    homeCard: {
      title: "Operations",
      description: "Command-center cockpit for dispatch, agents, approvals, and timeline review.",
      truthState: "read-only",
      primaryActionLabel: "Open Operations",
      safetyNote: "Control-plane visibility cockpit; no automatic backend dispatch from launcher.",
    },
    panels: [
      { id: "operations-top", title: "Surface strip", zone: "top", contentType: "pipeline" },
      { id: "operations-left", title: "Navigator", zone: "left", contentType: "tool-cards" },
      { id: "operations-center", title: "Command viewport", zone: "center", contentType: "custom" },
      { id: "operations-right", title: "Inspector", zone: "right", contentType: "inspector" },
      { id: "operations-bottom", title: "Summary drawer", zone: "bottom", contentType: "evidence" },
    ],
  }),
  createCockpitDefinition({
    id: "runtime",
    routeKey: "runtime",
    category: "operate",
    title: runtimeGuide.workspaceTitle,
    navLabel: runtimeGuide.navLabel,
    navSubtitle: runtimeGuide.navSubtitle,
    workspaceSubtitle: runtimeGuide.workspaceSubtitle,
    description: "Bridge health, executors, workspace posture, and governance cockpit.",
    truthState: "read-only",
    navTone: "neutral",
    navTooltip: runtimeGuide.tooltip,
    showInHomeLauncher: true,
    homeCard: {
      title: "Runtime",
      description: "Inspect bridge heartbeat, executor health, and governance posture before claiming admission scope.",
      truthState: "read-only",
      primaryActionLabel: "Open Runtime",
      safetyNote: "Status cockpit; does not mutate project content.",
    },
    panels: [
      { id: "runtime-top", title: "Surface strip", zone: "top", contentType: "pipeline" },
      { id: "runtime-left", title: "Navigator", zone: "left", contentType: "tool-cards" },
      { id: "runtime-center", title: "Runtime viewport", zone: "center", contentType: "custom" },
      { id: "runtime-right", title: "Inspector", zone: "right", contentType: "inspector" },
      { id: "runtime-bottom", title: "Summary drawer", zone: "bottom", contentType: "evidence" },
    ],
  }),
  createCockpitDefinition({
    id: "records",
    routeKey: "records",
    category: "inspect",
    title: recordsGuide.workspaceTitle,
    navLabel: recordsGuide.navLabel,
    navSubtitle: recordsGuide.navSubtitle,
    workspaceSubtitle: recordsGuide.workspaceSubtitle,
    description: "Evidence cockpit for runs, executions, artifacts, and events.",
    truthState: "read-only",
    navTone: "neutral",
    navTooltip: recordsGuide.tooltip,
    showInHomeLauncher: true,
    homeCard: {
      title: "Records",
      description: "Review persisted runs, executions, artifacts, and timeline events.",
      truthState: "read-only",
      primaryActionLabel: "Open Records",
      safetyNote: "Read-only evidence review cockpit.",
    },
    panels: [
      { id: "records-top", title: "Surface strip", zone: "top", contentType: "pipeline" },
      { id: "records-left", title: "Navigator", zone: "left", contentType: "tool-cards" },
      { id: "records-center", title: "Evidence viewport", zone: "center", contentType: "custom" },
      { id: "records-right", title: "Inspector", zone: "right", contentType: "inspector" },
      { id: "records-bottom", title: "Summary drawer", zone: "bottom", contentType: "evidence" },
    ],
  }),
];
